### ISSUE TITLE
[RFE] Allow policy generator to reference policies outside the directory

### ISSUE THREAD

**Issue by gnunn1** [stolostron/policy-generator-plugin#67]
In my setup I am using Argo CD to deploy Kyverno policies as I am sometimes doing demos with ACM and sometimes without but always have Argo deployed. I have a separate Argo Application that I use to deploy the ACM reporting policies where I use Kustomize to strip out the policy itself and just leave the part in for checking for PolicyReport.

As a result I have a parallel directory structure as follows:
- components
  - kyverno/overlays/policies
  - kyverno-acm/base

If I attempt to reference the policies in `kyverno/overlays/policies` from `kyverno-acm/base` I get the following error:

```
error processing the PolicyGenerator file '/tmp/kust-plugin-config-1018949722': the manifest path ../../kyverno/overlays/policies/validate-probes-policy.yaml is not in the same directory tree as the kustomization.yaml file
Error: failure in plugin configured via /tmp/kust-plugin-config-1018949722; exit status 1: exit status 1
```

I'm not sure why this restriction is there given that kustomize itself can reference files all over the place including remotely in git repos. I can symlink it for now but symlinks are not robust from a git perspective so would like to see this restriction removed.

**Comment by gnunn1** [comment]
Just an FYI that creating a symbolic link via symlink doesn't work either, same error.

**Comment by mprahl** [comment]
> Just an FYI that creating a symbolic link via symlink doesn't work either, same error.

This restriction is so that you can't reference a YAML file inside the container executing Kustomize outside of where your Git repo is cloned. This is to avoid leaking things such as secrets.

We may have gone too aggressive. Can you post a sample repo where this is failing?

**Comment by gnunn1** [comment]
My kyverno policies are located here:
https://github.com/gnunn-gitops/cluster-config/tree/main/components/apps/kyverno/overlays/policies

I am trying to reference them from here:
https://github.com/gnunn-gitops/cluster-config/tree/main/components/apps/kyverno-acm/base

Right now to workaround the issue I pushed things down a folder into `generate` with a script that copies the policies into the folder, generates the policies and then removes the folder. Also I am generating things locally not in Argo or ACM.

**Comment by dhaiducek** [comment]
@gnunn1 Circling back here, you can now point to a directory containing a `kustomization.yaml` in `policies[].manifests[].path`. This should give you the flexibility to point all sorts of places! 😄

**Comment by dhaiducek** [comment]
Please let us know whether this issue can be closed with this solution or there are further issues in this RFE.

**Comment by dhaiducek** [comment]
Closing as a solution has been implemented. Feel free to reopen if there are unresolved issues.
