### ISSUE TITLE
FYI: Your plugin has been added to Awesome Kustomize list

### ISSUE THREAD

**Issue by aabouzaid** [stolostron/policy-generator-plugin#89]
Hi :wave: 

I just started an [Awesome Kustomize](https://github.com/aabouzaid/awesome-kustomize/#generators) list :tada:
Because after using Kustomize for 3 years, there was no central place for Kustomize resources.

I've found your repo via a GitHub search, and I find it totally helpful, so I've added it to the list.

Thank you :rocket:

**Comment by dhaiducek** [comment]
Hi @aabouzaid! That's awesome--thank you so much!!! We really appreciate letting us know and being included in the list!
