### ISSUE TITLE
Apple Silicon build

### ISSUE THREAD

**Issue by kenmoini** [stolostron/policy-generator-plugin#94]
Any potential for a build for Apple Silicon, M1/M2?

**Comment by dhaiducek** [comment]
Hi @kenmoini! Are you not able to run the `darwin-arm64` binaries?

**Comment by kenmoini** [comment]
Haha - it does!  Whodathunkit, I keep forgetting Rosetta is a thing...sorry to bother, thanks for all the hard work y'all do!
